sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Bk0pMJ8wAtLUs/HkzMh81+Or7V9G2bu03A8eUqUQ/C1GAJBvKpC5H3w/wZasw3+ZkoDhKMRAOYHLqdLazjIP7dFwIJPsdoWCinO5gpf08oo8RP2so+tOiCRVBc5QeFEZ0AMHeNzndBmltvrKo/Vw3pFhFy/GVR+ae/bannUApX4ChrSt68e4ZezbkdI+DgrtepshfGLzrjXr/s0/TsQqGI8PFRd2Qzo2UT6PpaiaPdEW8b+FVo8x4bR655O7NY+kpAC/Xi8IHn+xi01eVdcjyd494RpannoZ4VUWCLAD4q9SLDARZvF7XT5zLzy6geh2+SiLqjE7tfpeuxM9HzLd/u+GCEqYNX49DyimbODwKrnToOSkAShh+Mo67jbrsEjnmeseFx15f1JIbjUKwiCZTWwwRFfmSHDFkbyio6oVsB24xP3dlkBpTUudwOAycz1Gfpqek9POxsqp4xvOktd6Zuh6DjE2kvJufhVXqJxIdTlkj3FQdsez50+S2XrA8hXYI9MMdsDG/Pxx7bms5BfjADzxryiSEyO4TlfXc+H7wlYTFNQIUw3adH6j5r083e4Ib7FGO+hbLPdyLVN2H5s+aJFE4TVtFw01yLLs5JZ3ggZvyd4z5J+lbdp9iQyt0KGIN/5xTHMN1OJi8Rud+Kq9aM07mkOv+lzOX4IdfvmE8rY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Adventures-of-Peregrine-Pickle_4084
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy